# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
from dotenv import load_dotenv

# Load environment variables from .env file in the api directory
load_dotenv(os.path.join(os.path.dirname(__file__), '.env'))

FMP_API_KEY = os.getenv("FMP_API_KEY")
if not FMP_API_KEY:
    raise ValueError("FMP_API_KEY environment variable is required. Please set it in .env file.")

FMP_ANALYST_ESTIMATES_URL = "https://financialmodelingprep.com/stable/analyst-estimates"
