# Code Generated by Sidekick is for learning and experimentation purposes only.
import os

FMP_API_KEY = os.getenv("FMP_API_KEY", "kFoyQBTilV6J4OIfCd9RdhTeTb8CeK5B")
FMP_ANALYST_ESTIMATES_URL = "https://financialmodelingprep.com/stable/analyst-estimates"
